language: java
sudo: false
install:
  - git clone https://github.com/iubar/iubar-desktop-api-client.git
  - cd iubar-desktop-api-client
  - mvn install -f pom_travis.xml  
script: 
  - cd presenze-client-test
  - mvn -f pom_travis.xml clean verify
