language: java
sudo: false
install:
  - git clone https://github.com/iubar/iubar-desktop-api-client.git
  - cd iubar-desktop-api-client
  - mvn -f pom_travis.xml install
script: 
  - mvn -f pom_travis.xml package
