language: java
sudo: false
install: true # The install step runs before script step, and with Maven you don't usually need the install step, at least I personally haven't ever found it useful — Maven will download dependencies on script step anyway
script: 
  - git clone https://github.com/iubar/iubar-desktop-api-client.git
  - cd iubar-desktop-api-client
  - mvn install -f pom_travis.xml
  - cd ..
  - cd presenze-client-test
  - mvn -f pom_travis.xml clean verify
